class FailureError {
  final String message;
  const FailureError({this.message = 'An unexpected error occurred.'});
}
